### ISSUE TITLE
Combine internal-transfer and offchain-withdraw into one circuit

### ISSUE THREAD

**Issue by yueawang** [Loopring/protocol3-circuits#37]
So far we have 2 different off-chain request types: internal-transfer and offchain-withdraw. They both use nonce. When Relay receives these requests, it needs to keep the sequence, which leads to a problem that Relay can not build large enough block, since they are 2 different types. As a result, we might see a bunch of trivial blocks rather than a few giant blocks.
What if we combine these 2 types into 1 circuit to make Relay able to build big blocks? There might be some waste in offchain-withdraw types as it is less complex than internal transfer, but consider the Relay's saving, I guess it is acceptable?
Please comment @letsgoustc @Brechtpd @hosschao @dong77 
Thanks!

**Comment by dong77** [comment]
I would strongly recommend to do so if possible mainly because of the nonce shared by these two circuits caused the relayer not able to create large blocks for those offchain requests. 

The new circuit may get bigger , but being able to create larger blocks will offset the overhead. 

发自我的iPhone

**Comment by Brechtpd** [comment]
We can solve this in two ways:
1. Merge the functionality in a single circuit
2. Use the trade history tree for these operations as well as it basically works like a 2D nonce.

Of course, 1. is the ideal solution. In the new trade circuit design, the trade circuit will already do lots of different things. I though about adding transfer functionality to it as well, and offchain withdrawals  seems to also make a lot of sense.

So yes, let's do this.

**Comment by dong77** [comment]
Sorry, Brecht, can you be more specific? Are you saying to merge both off-chain transfers and off-chain withdrawals into the settlement circuit so we end up with only one spot trading circuit, or just merge transfer and withdrawals into one?

Now we may have to consider how perpetual contract circuit is designed. Ideally Each account will have 3 nonces,  one for perpetual, one for spot trading, and a third one for all kinds of offchain transfers/withdrawals (including spot-to-spot transfers, perpetual-to-perpetual transfers, spot-to-perpetual transfers, perpetual-to-spot transfers, spot-to-layer1 transfers/withdrawals, perpetual-to-layer1 transfers/withdrawals). Then the ordering of these three main circuits will be de-coupled so the blocks can be potentially much bigger and the relayer’s throughput will also be higher.

**Comment by Brechtpd** [comment]
> Sorry, Brecht, can you be more specific? Are you saying to merge both off-chain transfers and off-chain withdrawals into the settlement circuit so we end up with only one spot trading circuit, or just merge transfer and withdrawals into one?

All into a single circuit (at least for all offchain request types, for the onchain requests this would need quite some refactoring so maybe it makes sense to do it, I'll be able to judge this better once I merged the offchain requests already). Spot trades, perpetual trades, spot <-> spot transfers, spot <-> margin transfers, withdrawals all done in a single circuit.

> Now we may have to consider how perpetual contract circuit is designed. Ideally Each account will have 3 nonces, one for perpetual, one for spot trading, and a third one for all kinds of offchain transfers/withdrawals (including spot-to-spot transfers, perpetual-to-perpetual transfers, spot-to-perpetual transfers, perpetual-to-spot transfers, spot-to-layer1 transfers/withdrawals, perpetual-to-layer1 transfers/withdrawals). Then the ordering of these three main circuits will be de-coupled so the blocks can be potentially much bigger and the relayer’s throughput will also be higher.

Trades don't use the account nonce value (trade history is used for this). A single nonce should be sufficient I think if all will be handled by a single circuit. But by merging all functionality into a single circuit we already have to update the trade history in the circuit, so the other requests could make use of that system as well for replay protection if needed for some reason.

**Comment by dong77** [comment]
> Trades don't use the account nonce value (trade history is used for this). 

Trades do need signing from the operator with a nonce. Maybe we can get rid of the nonce?

> A single nonce should be sufficient I think if all will be handled by a single circuit.

Definitely. The biggest challenge in our relayer is handling the packaging of different types of blocks. If the protocol supports fewer types of block, the optimization in the relayer will be maximized.

**Comment by Brechtpd** [comment]
> > Trades don't use the account nonce value (trade history is used for this).
> 
> Trades do need signing from the operator with a nonce. Maybe we can get rid of the nonce?

Yes, that's true. I think it's needed to be sure the block is unique when signed by the operator. It's likely this is only a problem with blocks that doesn't do anything (otherwise Merkle roots are changed and reverting the trade history isn't possible, so going back to an old Merkle root when something changed seems impossible) but I think it's still best to do to be 100% sure. But it's just the nonce of the operator which won't do many operations (except deposits/withdrawals which don't need nonces, so the operator can just use onchain requests for these and no need to worry about nonces at all).

But yeah, with a single circuit we don't even have to worry about things like this. :)

**Comment by yueawang** [comment]
Closed, will be done by 3.6.
