### ISSUE TITLE
Some gadgets does similar job, should we just keep the better one, if exist.

### ISSUE THREAD

**Issue by yueawang** [Loopring/protocol3-circuits#40]
For example:
1. The subadd_gadget is used by TransferGadget, as below:
![image](https://user-images.githubusercontent.com/26989346/88817116-b4dd1c80-d1ef-11ea-9b3e-faf0efc56d3a.png)
I know it calc add simultaneously, let's focus on sub part first. 

2. The SubGadget used in balance calculation.
![image](https://user-images.githubusercontent.com/26989346/88817056-a8f15a80-d1ef-11ea-8e24-2f2be4b53427.png)

Both these 2 do sub calculations, but they have different implementations.
I just wonder if one of them is better than the other, from saving the number of constraints point of view. If so, maybe we can upgrade those less efficient.
Thanks!

**Comment by Brechtpd** [comment]
We need separate sub and add gadgets, so it makes sense to just switch our only use of `subadd_gadget` in `TransferGadget` to use `SubGadget` and `AddGadget` instead. This won't have any significant impact on the constraints either way (I think it will reduce the number of constraints a tiny bit actually, but won't matter).

**Comment by yueawang** [comment]
Thanks @Brechtpd. Yes, that's what I thought, let's see if there are more gadgets that can be switched and hopes the sum of those switches gives a big enough impact.
